git test

diff --git a/.github/workflows/android-tests.yml b/.github/workflows/android-tests.yml
--- a/.github/workflows/android-tests.yml
+++ b/.github/workflows/android-tests.yml
@@ -82,12 +82,13 @@ jobs:
 
       - name: ❌ Force failure (test step)
         run: exit 1
-      - name: ❌ Force failure (test step)
-        if: always()
-        run: exit 1
 
+      # - name: ❌ Force failure (test step)
+      #   if: always()
+      #   run: exit 1
       - name: ✅ Force success (test step)
         run: exit 0
+
       - name: run tests
         id: emulator
         uses: reactivecircus/android-emulator-runner@v2
@@ -104,7 +105,7 @@ jobs:
             echo "Emulator started and boot completed!" && set +e && npm run test; EXIT_CODE=$?; set -e; echo "wdio_exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT; exit $EXIT_CODE
 
       - name: ✉️ Send Email Notification on Failure
-        if: always() && (failure() && !steps.emulator) || (steps.emulator && steps.emulator.outcome == 'failure' && steps.emulator.outputs.wdio_exit_code == '1')
+        if: ( always() && (failure() && !steps.emulator)) || ( steps.emulator && steps.emulator.outcome == 'failure' && steps.emulator.outputs.wdio_exit_code == '1' )
         run: |
          echo "📧 Mail sent"
          echo "emulator step present: ${{ steps.emulator != '' }}"
