Test allure

diff --git a/.github/workflows/android-tests.yml b/.github/workflows/android-tests.yml
--- a/.github/workflows/android-tests.yml
+++ b/.github/workflows/android-tests.yml
@@ -38,24 +38,38 @@ jobs:
     timeout-minutes: 20
 
     steps:
-      # - name: Checkout testing repo
-      #   uses: actions/checkout@v4
+      - name: Checkout testing repo
+        uses: actions/checkout@v4
 
-      # - name: Use desired version of NodeJS
-      #   uses: actions/setup-node@v4
-      #   with:
-      #     node-version: 24
-      #     cache: npm
+      - name: Use desired version of NodeJS
+        uses: actions/setup-node@v4
+        with:
+          node-version: 24
+          cache: npm
 
-      # - name: Install Dependencies
-      #   run: |
-      #     npm ci || npm i
-
-      - name: Enable KVM
+      - name: Install Dependencies
         run: |
-          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
-          sudo udevadm control --reload-rules
-          sudo udevadm trigger --name-match=kvm
+          npm ci || npm i
+      - name: Run tests
+        run: |
+          npm run tests
+
+      - name: 📊 Generate Test report
+        run: |
+          npm run report:generate
+
+      - name: 🚀 Deploy Allure Report to GitHub Pages
+        if: always()
+        uses: peaceiris/actions-gh-pages@v4
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_dir: ./allure-report
+
+      # - name: Enable KVM
+      #   run: |
+      #     echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
+      #     sudo udevadm control --reload-rules
+      #     sudo udevadm trigger --name-match=kvm
 
       # - name: AVD cache
       #   uses: actions/cache@v4
@@ -79,10 +93,6 @@ jobs:
       #     emulator-options: -no-window -noaudio -no-boot-anim -gpu swiftshader_indirect
       #     script: echo "Generated AVD snapshot for caching."
 
-      # - name: ❌ Force failure (test step)
-      #   id: forcefail
-      #   run: exit 1
-
       - name: run tests
         id: emulator
         uses: reactivecircus/android-emulator-runner@v2
@@ -98,54 +108,49 @@ jobs:
           script: |
             echo "Emulator started and boot completed!" && set +e && true; EXIT_CODE=$?; set -e; echo "wdio_exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT; exit $EXIT_CODE
 
-      - name: Simple Log
-        if: always()
-        run: |
-          echo "steps.emulator.outcome = ${{ steps.emulator.outcome }}"
-          echo "steps.emulator.outcome.outputs = ${{ steps.emulator.outcome.outputs }}"
 
-      - name: ✉️ Send Email Notification on Failure
-        if: always() && failure() &&  (steps.emulator.outcome == 'skipped') || (steps.emulator.outcome == 'failure' && steps.emulator.outputs.wdio_exit_code == '')
-        id: emaild
-        run: |
-          echo "📧 Mail sent"
-          echo "steps.emulator.outcome = ${{ steps.emulator.outcome }}"
-          echo "steps.emulator.outcome.outputs = ${{ steps.emulator.outcome.outputs }}"
+    #   - name: ✉️ Send Email Notification on Failure
+    #     if: always() && failure() && (steps.emulator.outcome == 'skipped') || (steps.emulator.outcome == 'failure' && steps.emulator.outputs.wdio_exit_code == '')
+    #     id: emaild
+    #     run: |
+    #       echo "📧 Mail sent"
+    #       echo "steps.emulator.outcome = ${{ steps.emulator.outcome }}"
+    #       echo "steps.emulator.outcome.outputs = ${{ steps.emulator.outcome.outputs }}"
 
 
 
-    # if: failure() && steps.emulator.outcome == 'failure' || steps.emulator.outcome == 'failure' && steps.emulator.outputs.wdio_exit_code == ''
+    # # if: failure() && steps.emulator.outcome == 'failure' || steps.emulator.outcome == 'failure' && steps.emulator.outputs.wdio_exit_code == ''
 
-    # - name: Archive test artifacts (screenshots, HTML snapshots, Reports)
-    #   if: always()
-    #   uses: actions/upload-artifact@v4
-    #   with:
-    #     name: test-artifact
-    #     path: |
-    #       screencasts
-    #     if-no-files-found: ignore
-    #     retention-days: 1
+    # # - name: Archive test artifacts (screenshots, HTML snapshots, Reports)
+    # #   if: always()
+    # #   uses: actions/upload-artifact@v4
+    # #   with:
+    # #     name: test-artifact
+    # #     path: |
+    # #       screencasts
+    # #     if-no-files-found: ignore
+    # #     retention-days: 1
 
-    # script: |
-    # echo "Emulator started and boot completed!" && set +e && npx wdio run wdio.conf.js; EXIT_CODE=$?; set -e; echo "wdio_exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT; exit $EXIT_CODE
+    # # script: |
+    # # echo "Emulator started and boot completed!" && set +e && npx wdio run wdio.conf.js; EXIT_CODE=$?; set -e; echo "wdio_exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT; exit $EXIT_CODE
 
-    # - name: Check WDIO result
-    #   if: always()
-    #   run: |
-    #     echo "WDIO exit code: ${{ steps.emu.outputs.wdio_exit_code}}"
-    #     echo "WDIO exit code: ${{ steps.emu.outcome }}"
+    # # - name: Check WDIO result
+    # #   if: always()
+    # #   run: |
+    # #     echo "WDIO exit code: ${{ steps.emu.outputs.wdio_exit_code}}"
+    # #     echo "WDIO exit code: ${{ steps.emu.outcome }}"
 
-    # - name: Send Email
-    #   if: failure() && steps.emu.outcome == 'failure' && steps.emu.outputs.wdio_exit_code == ''
-    #   run: |
-    #     node ./utils/sendAcionfailMail.js
+    # # - name: Send Email
+    # #   if: failure() && steps.emu.outcome == 'failure' && steps.emu.outputs.wdio_exit_code == ''
+    # #   run: |
+    # #     node ./utils/sendAcionfailMail.js
 
-    # - name: Handle emulator failure
-    #   if: failure() && steps.emu.outcome == 'failure' && steps.emu.outputs.wdio_exit_code == ''
-    #   run: |
-    #     echo "Step failed due to emulator issues (not test failures)"
+    # # - name: Handle emulator failure
+    # #   if: failure() && steps.emu.outcome == 'failure' && steps.emu.outputs.wdio_exit_code == ''
+    # #   run: |
+    # #     echo "Step failed due to emulator issues (not test failures)"
 
-    # - name: Handle emulator failure
-    #   if: failure() && steps.emu.outcome == 'failure' && steps.emu.outputs.wdio_exit_code == '1'
-    #   run: |
-    #     echo "test failed(not test failures)"
+    # # - name: Handle emulator failure
+    # #   if: failure() && steps.emu.outcome == 'failure' && steps.emu.outputs.wdio_exit_code == '1'
+    # #   run: |
+    # #     echo "test failed(not test failures)"
